services:
    app:
       build:
           context: .
       ports:
           -  "5005"
    nginx: 
        image: nginx:latest
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - app
        ports:
        - "8080:8080"